### PR TITLE
Some minor improvements

### PR DESCRIPTION
**Pull request by tautcony**
Add some summary and improve the property CreationDate.

### CODE REVIEW

**Comment by hennyce** [comment]
Hello, Can anybody tell me how to get the seeds & peers for a torrent ?

**Comment by tautcony** [comment]
No, there is no such infomation in the torrent file.

> - **Seeds** displays the number of seeds you are connected to, and the number of seeds in the swarm in the parentheses. The number in the swarm is collected from the tracker and other methods of exchanging peers, such as DHT or Peer Exchange.
> - **Peers** displays the number of peers you are connected to, and the number of peers in the swarm in the parentheses. The number in the swarm is collected from the tracker and other methods of exchanging peers, such as DHT or Peer Exchange.

So, these two would not to be known before you begin to use the torrent to downloading the files.

**Comment by hennyce** [comment]
Thanks for the quick response tautcony.

What I mean is that I need to display the number of peers / seeds in the swarm by retrieving the information from the DHT or Peer Exchange.
I know this the seeds / peers changes so I need to retrieve it dynamically or each time a torrent is decoded

Is something like this possible ?
If not do you know any c# library that can help me ?

**Comment by tautcony** [comment]
These info is not stored in the torrent file.
What you need (MAYBE) is a library like MonoTorrent or the C# wrapper for the libtorrent .

I have never use these library currently, so no further advice can I provide, sorry for that.

**Comment by hennyce** [comment]
Ok, thanks

**Comment by Krusen** [comment]
@tautcony Thanks for the contribution. I've just changed `CreationDate` to return `DateTime.MinValue` instead of `_epoch` as I thought that was maybe more meaningful.

**Pull request merged**
